version: '3.7'

services:

  pg:
    command: ["postgres", "-c", "logging_collector=on", "-c", "log_statement=all"]

  web:
    build:
      context: .
      args:
          develop: 1
    command: "python manage.py runserver 0.0.0.0:8888"
    ports:
      - "8888:8888"
    environment:
      - DJANGO_DEBUG=True
